spring:
  datasource:
    url: jdbc:h2:file:~/message-board
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  sql:
    init:
      mode: always       # 启用 SQL 初始化
      platform: h2       # 指定数据库平台

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect